BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Cetak] (
    [ITEMCODE] NVARCHAR(80) NOT NULL,
    [NAMAITEM] NVARCHAR(120) NOT NULL,
    [HARGA] FLOAT(53) NOT NULL,
    [DIVISI] NVARCHAR(80) NOT NULL,
    [STATUS] NVARCHAR(2) NOT NULL,
    [TANGGAL] DATETIME2 NOT NULL,
    CONSTRAINT [Cetak_pkey] PRIMARY KEY CLUSTERED ([ITEMCODE])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
